name: Cloud-TPU-CI-Nightly

on:
  schedule:
    - cron: "0 12 * * *" # Daily at 12:00 UTC
  workflow_dispatch: # allows triggering the workflow run manually
  repository_dispatch: # allows triggering the workflow via HTTP

jobs:
  cloud-tpu-test:
    runs-on: tpu
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]  # TODO(jakevdp): update to 3.11 when available.
    outputs:
      artifacts_availability: ${{ steps.status.outputs.ARTIFACTS_AVAILABLE }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install JAX test requirements
        run: |
          pip install -r build/test-requirements.txt
          pip install pytest-reportlog
      - name: Install JAX
        run: |
          pip install .[tpu] -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
      - name: Run tests
        if: success()
        id: status
        env:
          JAX_PLATFORMS: tpu,cpu
        run: |
          pytest --tb=short tests/compilation_cache_test.py \
              || (
                echo '::set-output name=ARTIFACTS_AVAILABLE::true' && false
              )
        # run: |
        #   pytest --tb=short \
        #       --deselect tests/callback_test.py \
        #       --deselect tests/checkify_test.py \
        #       --deselect tests/debugger_test.py \
        #       --deselect tests/debugging_primitives_test.py \
        #       --deselect tests/jaxpr_effects_test.py-rf \
        #       --report-log output-${{ matrix.python-version }}-log.jsonl \
        #       tests \
        #       || (
        #         echo '::set-output name=ARTIFACTS_AVAILABLE::true' && false
        #       )
      - name: Upload artifacts
        if: |
          failure()
          # && steps.status.outcome == 'failure'
          # && github.event_name == 'schedule'
          # && github.repository == 'google/jax'
        uses: actions/upload-artifact@v3
        with:
          name: output-${{ matrix.python-version }}-log.jsonl
          path: output-${{ matrix.python-version }}-log.jsonl
          retention-days: 5
