name: Cloud TPU nightly

on:
  schedule:
    - cron: "0 14 * * *"  # daily at 7am PST
  workflow_dispatch:  # allows triggering the workflow run manually

# This should also be set to read-only in the project settings, but it's nice to
# document and enforce the permissions here.
permissions:
  contents: read

jobs:
  cloud-tpu-test:
    strategy:
      fail-fast: false  # don't cancel all jobs on failure
      matrix:
        python-version: ["3.10"]  # TODO(jakevdp): update to 3.11 when available.
        jaxlib-version: [latest]
    steps:
      - name: test step
        run: exit 1
      - name: chat
        if: failure()
        run: |
            curl --location --request POST '${{ secrets.ACTION_FAILURE_WEBHOOK }}' \
            --header 'Content-Type: application/json' \
            --data-raw "{
            'text': '$GITHUB_JOB job failed: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID'
            }"
